### ISSUE TITLE
when using with rpi3: ERROR: No entry -march=.. found in: 

### ISSUE THREAD

**Issue by stefson** [hartwork/resolve-march-native#4]
hey there, I discovered this tiny little program recently and found it to be usefull. Testing it on an rpi3b+ with gentoo running on it I got this rather short error: 

```
resolve-march-native
ERROR: No entry -march=.. found in: 
```

I'm very bad at debugging python, and even though your code base is really small I was unable to find the error on my own. Do you maybe depend on some particular kernel feature?

**Comment by hartwork** [comment]
Hi @stefson , can you share the output of `resolve-march-native --debug` from the rpi3b+?

**Comment by stefson** [comment]
of course, I overlooked the debug switch from resolve-march-native binary. Here's the output: 

```
resolve-march-native --debug
# gcc -S -fverbose-asm -o /tmp/tmpoij4vqey/march_native.s /tmp/tmpoij4vqey/empty.c -march=native
Flags extracted: 
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.8/resolve-march-native", line 51, in main
    native_unrolled_flag_set = Engine(options.gcc, options.debug).run(options)
  File "/usr/lib/python3.8/site-packages/resolve_march_native/engine.py", line 120, in run
    arch = self._extract_arch_from_flags(march_native_flag_set)
  File "/usr/lib/python3.8/site-packages/resolve_march_native/engine.py", line 27, in _extract_arch_from_flags
    raise ValueError('No entry -march=.. found in: %s' % ' '.join(sorted(flags)))
ValueError: No entry -march=.. found in: 
ERROR: No entry -march=.. found in: 
```

**Comment by hartwork** [comment]
Okay thanks, my bad. Could you share the output of…
```
cd "$(mktemp -d)" && touch empty.c && gcc -S -fverbose-asm -o /dev/stdout empty.c -march=native
```
…as well?

**Comment by stefson** [comment]
sure, here's the command: `cd "$(mktemp -d)" && touch empty.c && gcc -S -fverbose-asm -o /dev/stdout empty.c -march=native`

and the output: 
```
	.arch armv8-a+crc
	.file	"empty.c"
// GNU C17 (Gentoo 9.3.0-r1 p3) version 9.3.0 (aarch64-unknown-linux-gnu)
//	compiled by GNU C version 9.3.0, GMP version 6.2.0, MPFR version 4.0.2, MPC version 1.1.0, isl version none
// warning: MPFR header version 4.0.2 differs from library version 4.1.0.
// warning: MPC header version 1.1.0 differs from library version 1.2.0.
// GGC heuristics: --param ggc-min-expand=92 --param ggc-min-heapsize=117454
// angegebene Optionen:  empty.c -mlittle-endian -mabi=lp64
// -march=armv8-a+crc -auxbase-strip /dev/stdout -fverbose-asm
// eingeschaltete Optionen:  -fPIC -fPIE -faggressive-loop-optimizations
// -fassume-phsa -fasynchronous-unwind-tables -fauto-inc-dec -fcommon
// -fdelete-null-pointer-checks -fdwarf2-cfi-asm -fearly-inlining
// -feliminate-unused-debug-types -ffp-int-builtin-inexact -ffunction-cse
// -fgcse-lm -fgnu-runtime -fgnu-unique -fident -finline-atomics
// -fipa-stack-alignment -fira-hoist-pressure -fira-share-save-slots
// -fira-share-spill-slots -fivopts -fkeep-static-consts
// -fleading-underscore -flifetime-dse -flto-odr-type-merging -fmath-errno
// -fmerge-debug-strings -fomit-frame-pointer -fpeephole -fplt
// -fprefetch-loop-arrays -freg-struct-return
// -fsched-critical-path-heuristic -fsched-dep-count-heuristic
// -fsched-group-heuristic -fsched-interblock -fsched-last-insn-heuristic
// -fsched-rank-heuristic -fsched-spec -fsched-spec-insn-heuristic
// -fsched-stalled-insns-dep -fschedule-fusion -fsemantic-interposition
// -fshow-column -fshrink-wrap-separate -fsigned-zeros
// -fsplit-ivs-in-unroller -fssa-backprop -fstack-protector-strong
// -fstdarg-opt -fstrict-volatile-bitfields -fsync-libcalls -ftrapping-math
// -ftree-cselim -ftree-forwprop -ftree-loop-if-convert -ftree-loop-im
// -ftree-loop-ivcanon -ftree-loop-optimize -ftree-parallelize-loops=
// -ftree-phiprop -ftree-reassoc -ftree-scev-cprop -funit-at-a-time
// -funwind-tables -fverbose-asm -fzero-initialized-in-bss
// -mfix-cortex-a53-835769 -mfix-cortex-a53-843419 -mglibc -mlittle-endian
// -momit-leaf-frame-pointer -mpc-relative-literal-loads

	.text
	.ident	"GCC: (Gentoo 9.3.0-r1 p3) 9.3.0"
	.section	.note.GNU-stack,"",@progbits
```

does it make sense for you? :-)

**Comment by hartwork** [comment]
Thanks a lot, I will have a closer look!

**Comment by hartwork** [comment]
Seems to have to do with the C++ style comments, see #5. I can add a regression test (like [these](https://github.com/hartwork/resolve-march-native/tree/master/resolve_march_native/test/data)) for this if you can share the files `native.s` and `explicit.s` produced by these commands:

```console
cd "$(mktemp -d)"
touch empty.c
LC_ALL=C gcc -S -fverbose-asm -o   native.s empty.c -march=native
LC_ALL=C gcc -S -fverbose-asm -o explicit.s empty.c -march=armv8-a+crc
```

The `LC_ALL=C` makes sure that GCC doesn't talk German to us. Thanks in advance!

**Comment by stefson** [comment]
ah yeah, I forgot to disable local in the initial reports, sorry about that :) 

here are the files you asked for: [files.tar.gz](https://github.com/hartwork/resolve-march-native/files/5321942/files.tar.gz)

**Comment by hartwork** [comment]
Awesome, thank you!

**Comment by hartwork** [comment]
PS: Release 1.0.0 with the fix just hit PyPI and Gentoo, enjoy :smiley:
